In [5]:
import pandas as pd
import numpy as np

In [4]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 0.09963827 -0.60726075 -1.49698657  0.84460141]

<class 'pandas.Series'>
0    0.099638
1   -0.607261
2   -1.496987
3    0.844601
dtype: float64

In [6]:
# A series from a numpy array 
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [7]:
# A series from a list of strings with default index
pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: str

In [8]:
# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [9]:
pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

In [10]:
# Define a series
s = pd.Series([91,-999,25,-999],index=['A', 'B', 'C', 'D'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [11]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [12]:
# Series with NAs in it
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [13]:
# Check if series has NAs
s.hasnans

True

In [14]:
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [6]:
s = pd.Series([91,-999,25,-999],index=['A', 'B', 'C', 'D'])
print(s)

A     91
B   -999
C     25
D   -999
dtype: int64

In [8]:
s = s.mask(s == -999)
s

A    91.0
B     NaN
C    25.0
D     NaN
dtype: float64

In [10]:
d = {'col_name_1': pd.Series(np.arange(3)), 
    'col_name_2':pd.Series([3.1, 3.2, 3.3])}

In [12]:
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [14]:
df.columns = ['C1', 'C2']
df

   C1   C2
0   0  3.1
1   1  3.2
2   2  3.3

In [16]:
df.index = [1,2,3]
df

   C1   C2
1   0  3.1
2   1  3.2
3   2  3.3